site_name: Webstede.info - Learning by Doing
site_url: https://annelieshofstede.github.io/webstede_info
theme:
  name: material
  language: nl
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Donkere modus
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Lichte modus
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list